In [1]:
import nltk

In [2]:
from nltk.corpus import brown

In [6]:
print(brown.categories())
print(len(brown.categories()))
#Here is different categories that contains words those are most frequently or mostly used in that feild

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [15]:
data=brown.sents(categories='government')
print(data)
print(len(data))

[['The', 'Office', 'of', 'Business', 'Economics', '(', 'OBE', ')', 'of', 'the', 'U.S.', 'Department', 'of', 'Commerce', 'provides', 'basic', 'measures', 'of', 'the', 'national', 'economy', 'and', 'current', 'analysis', 'of', 'short-run', 'changes', 'in', 'the', 'economic', 'situation', 'and', 'business', 'outlook', '.'], ['It', 'develops', 'and', 'analyzes', 'the', 'national', 'income', ',', 'balance', 'of', 'international', 'payments', ',', 'and', 'many', 'other', 'business', 'indicators', '.'], ...]
3032


In [16]:
data=' '.join(data[1])
data

'It develops and analyzes the national income , balance of international payments , and many other business indicators .'

### Bag of Words

#### Steps to involve in this
1.Get the data/corpus
2.Tokenization, stopword removal
3.Stemming/lemmatization
4.Building a vocab
5.Vectorization
6.classification

In [17]:
#nltk tokenization & stopword removal
document='''It was very pleasant day. The weather was cool and there were light showers.I went to market to buy some fruits. '''
sentence='Send all the 50 documents related to chapters 1,2,3 at dipika@cb.com'

In [18]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [22]:
sentence_token=sent_tokenize(document)
print(sentence_token)
print(len(sentence_token))
# as sent_tokenize separate the documents where it sees fullstop.

['It was very pleasant day.', 'The weather was cool and there were light showers.I went to market to buy some fruits.']
2


In [23]:
words=word_tokenize(sentence)
print(words)
print(len(words))

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'dipika', '@', 'cb.com']
13


In [35]:
#stopwords
from nltk.corpus import stopwords
sw=set(stopwords.words('english'))
print(sw)
print(len(sw))

{'any', 'be', 'when', 'hers', 'ain', 'my', 'being', "couldn't", 'been', 'their', 'own', 'some', 'hasn', 'through', 'me', "haven't", 'yourselves', 'with', 'doing', 'because', 'which', "didn't", "wasn't", 'down', 'mightn', 'she', 'its', 's', 'aren', 'other', 'these', 'there', 'and', "shouldn't", 'few', 'wasn', "mightn't", 'how', 'above', 'theirs', "hasn't", 'only', 'him', "isn't", 'those', 'into', "aren't", 'he', 'during', 'couldn', 'ma', 'no', "hadn't", 'to', 'yours', 'will', 'now', 'we', 'same', 'from', 'weren', "doesn't", 'is', 'wouldn', 'o', 'where', 'do', "you'd", 'a', 'after', 'll', 'what', "you've", 'by', 'whom', 'themselves', 'about', 'so', "shan't", 'too', 'am', 'why', 'or', 'not', 'ours', 'but', 'very', 'your', 'm', "mustn't", 'again', 'haven', 'while', 'most', 'himself', 'that', 'it', 'over', 'off', 'y', 'in', 'didn', 'yourself', 'each', 'for', 'once', 'his', 'at', 'on', "she's", 'if', 'd', 'they', "that'll", 'all', 'the', 'more', 'than', 'just', 'until', 'under', 'then', 'did

In [37]:
#Function to remove stopwords
def remove_stopword(text,stopwords):
    useful_words=[w for w in text if w not in stopwords]
    return useful_words

In [39]:
remove_stopword(document.split(),sw)
#use split orelse it will iterate with letters

['It',
 'pleasant',
 'day.',
 'The',
 'weather',
 'cool',
 'light',
 'showers.I',
 'went',
 'market',
 'buy',
 'fruits.']

### Stemming

Process of transforming verbs or plural words into their radical form
Preserve the semantics of the sentence without increasing the number of unique tokens.
Example=jumps,jumpping,jumped,jump==>jump

In [44]:
from nltk.stem import PorterStemmer,SnowballStemmer,RegexpStemmer
from nltk.stem.lancaster import LancasterStemmer

In [51]:
text=['jumps','writing','hearing','noisy','attractive']
ps=PorterStemmer()
for word in text:
    word=ps.stem(word.lower())
    print(word)

jump
write
hear
noisi
attract


In [54]:
sb=SnowballStemmer('english')
print(sb.stem('attractive'))
print(SnowballStemmer('french').stem('beautiful'))
print(SnowballStemmer('english').stem('beautiful'))

attract
beautiful
beauti


### Lemmatization

In [60]:
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer() 

In [64]:
print("rocks :", lemmatizer.lemmatize("rocks")) 
print("corpora :", lemmatizer.lemmatize("corpora")) 
  
# a denotes adjective in "pos" 
print("better :", lemmatizer.lemmatize("better", pos ="a")) 

rocks : rock
corpora : corpus
better : good


Building Vocab & Vectorization

In [65]:
#Building vocab & vectorization
corpus=[
    '''When compared to other countries with similar or higher case load, India called 
    its strict lockdown at a much earlier point on its case and death curves. 
    These 18 other countries had more than 500 cases when they called their strictest lockdown, 
    while India had 320. Again, India had only four deaths on March 22, 
    when its score reached 100, while most countries had more deaths at that point (except Switzerland; no deaths). '''
]

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [85]:
vectorize=CountVectorizer()
vectorized_corpus=vectorize.fit_transform(corpus)
print(vectorize.get_feature_names())

['100', '18', '22', '320', '500', 'again', 'and', 'at', 'called', 'case', 'cases', 'compared', 'countries', 'curves', 'death', 'deaths', 'earlier', 'except', 'four', 'had', 'higher', 'india', 'its', 'load', 'lockdown', 'march', 'more', 'most', 'much', 'no', 'on', 'only', 'or', 'other', 'point', 'reached', 'score', 'similar', 'strict', 'strictest', 'switzerland', 'than', 'that', 'their', 'these', 'they', 'to', 'when', 'while', 'with']


In [89]:
print(vectorized_corpus.shape)
vectorized_corpus

(1, 50)


<1x50 sparse matrix of type '<class 'numpy.int64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [90]:
vectorized_corpus=vectorized_corpus.toarray()
vectorized_corpus

array([[1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 3, 1, 1, 3, 1, 1, 1, 4, 1, 3,
        3, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 3, 2, 1]], dtype=int64)

In [91]:
print(vectorize.vocabulary_)

{'when': 47, 'compared': 11, 'to': 46, 'other': 33, 'countries': 12, 'with': 49, 'similar': 37, 'or': 32, 'higher': 20, 'case': 9, 'load': 23, 'india': 21, 'called': 8, 'its': 22, 'strict': 38, 'lockdown': 24, 'at': 7, 'much': 28, 'earlier': 16, 'point': 34, 'on': 30, 'and': 6, 'death': 14, 'curves': 13, 'these': 44, '18': 1, 'had': 19, 'more': 26, 'than': 41, '500': 4, 'cases': 10, 'they': 45, 'their': 43, 'strictest': 39, 'while': 48, '320': 3, 'again': 5, 'only': 31, 'four': 18, 'deaths': 15, 'march': 25, '22': 2, 'score': 36, 'reached': 35, '100': 0, 'most': 27, 'that': 42, 'except': 17, 'switzerland': 40, 'no': 29}


In [94]:
print(len(vectorize.vocabulary_))
print(len(vectorize.vocabulary_.keys()))

50
50


In [96]:
#Reverse Mapping
print(len(vectorized_corpus))
print(type(vectorized_corpus))

1
<class 'numpy.ndarray'>


In [100]:
vectorized_corpus

array([[1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 3, 1, 1, 3, 1, 1, 1, 4, 1, 3,
        3, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 3, 2, 1]], dtype=int64)

In [101]:
corpus=vectorize.inverse_transform(vectorized_corpus)
corpus

[array(['100', '18', '22', '320', '500', 'again', 'and', 'at', 'called',
        'case', 'cases', 'compared', 'countries', 'curves', 'death',
        'deaths', 'earlier', 'except', 'four', 'had', 'higher', 'india',
        'its', 'load', 'lockdown', 'march', 'more', 'most', 'much', 'no',
        'on', 'only', 'or', 'other', 'point', 'reached', 'score',
        'similar', 'strict', 'strictest', 'switzerland', 'than', 'that',
        'their', 'these', 'they', 'to', 'when', 'while', 'with'],
       dtype='<U11')]

In [111]:
print(type(corpus))
s=vectorized_corpus.tobytes()
s=str(s)
type(s)

<class 'list'>


str

In [112]:
from nltk.tokenize import RegexpTokenizer

In [181]:
# A tokenizer that splits a string using a regular expression, which
# matches either the tokens or the separators between tokens.

#Indian and indian are same
tokenizer = RegexpTokenizer('\w+|\$[\d\.]+|\S+')

In [184]:
def Mytoken(document,stopwords):
    word=tokenizer.tokenize(document.lower())
    #remove stopwords
    word=[w for w in document if w not in stopwords]
    #word=" ".join(word)
    return word
    

In [199]:
corpus= '''When compared to other countries with similar or higher case load, India called 
    its strict lockdown at a much earlier point on its case and death curves. 
    These 18 other countries had more than 500 cases when they called their strictest lockdown, 
    while India had 320. Again, India had only four deaths on March 22, 
    when its score reached 100, while most countries had more deaths at that point (except Switzerland; no deaths). '''

token=Mytoken(corpus,set(stopwords.words('english')))
#token=','.join(token)
#token

In [201]:
sent_1=['this is good movie']
sent_2=['this is not good movie']
doc=[sent_1[0],sent_2[0]]


['this is good movie', 'this is not good movie']

In [206]:
from sklearn.feature_extraction.text import CountVectorizer

In [213]:
cv=CountVectorizer()

In [214]:
print(cv.fit_transform(doc).toarray())
cv.vocabulary_

[[1 1 1 0 1]
 [1 1 1 1 1]]


{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'not': 3}

In [215]:
cv=CountVectorizer(ngram_range=(3,3))
cv.fit_transform(doc).toarray()

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1]], dtype=int64)

In [216]:
cv.vocabulary_

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

In [217]:
sent_3=['this was good movie']
corpus=[sent_1[0],sent_2[0],sent_3[0]]
corpus

['this is good movie', 'this is not good movie', 'this was good movie']

In [218]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [223]:
tfidf=TfidfVectorizer()
vc=tfidf.fit_transform(corpus).toarray()
print(tf)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]]


In [225]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'not': 3, 'was': 5}

In [235]:
tfidf=TfidfVectorizer(ngram_range=(2,2))
vc=tfidf.fit_transform(corpus).toarray()
print(tf)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]]


In [236]:
tfidf.vocabulary_

{'this is': 4,
 'is good': 1,
 'good movie': 0,
 'is not': 2,
 'not good': 3,
 'this was': 5,
 'was good': 6}